  - name: add application user
    ansible.builtin.user:
      name: roboshop
  
  - name: remove app directory if exist already
    ansible.builtin.file:
      path: /app
      state: absent 
    
  - name: create a directory 
    ansible.builtin.file:
      path: /app
      state: directory

  - name: "download {{component}} code" 
    ansible.builtin.get_url:
      url: "https://roboshop-builds.s3.amazonaws.com/{{component}}.zip"
      dest: "/tmp/{{component}}.zip"
    
  - name: "unzip the {{component}} code"
    ansible.builtin.unarchive:
      src: "/tmp/{{component}}.zip"
      dest: /app
      remote_src: yes